# Generated by Django 2.1.1 on 2018-09-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynoteapp', '0003_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Публичная заметка'),
        ),
        migrations.AlterField(
            model_name='note',
            name='favorites',
            field=models.BooleanField(default=False, verbose_name='Избранная'),
        ),
    ]
